from model import *
import shutil,hashlib
r=json.load(open(OUT/'validation.json'));assert r['passed'];stats=json.load(open(OUT/'refinement.json'));alpha=json.load(open(OUT/'damping.json'))['venousDisplacementFraction'];measured=[]
for side in ['right','left']:
 n='vein.cavernous.'+side;old,_=load(n);new,_=load(n,True);slices=[]
 for y in [-54,-50,-46,-42,-38]:
  m=np.abs(old[:,1]-y)<.5;top=m&(old[:,2]>=np.percentile(old[m,2],90));slices.append({'yMm':y,'meanUpperSurfaceDisplacementMm':float((old[top,2]-new[top,2]).mean()),'roofBeforeMm':float(old[m,2].max()),'roofAfterMm':float(new[m,2].max())})
 measured.append({'side':side,'slices':slices})
stats['finalPosteriorHeight']=measured;stats['acceptedVenousDisplacementFraction']=alpha;stats['initialUndampedMeasurements']=True;(OUT/'refinement.json').write_text(json.dumps(stats,indent=2))
space=r['checks']['fullSurfaceConstraints']['sides'];njoins=len(r['checks']['physicalJunctions']['junctions'])
lines=['# ICA / cavernous sinus refinement, v0.9.33','','Baseline: final v0.9.32 snapshot with local branch-clearance corrections. This is an anatomical review model.','','## Changes','','The posterior sinus roof is reduced while its anterior roof and fixed ophthalmic relationships remain close to the accepted baseline. The ICA is not lowered. Arterial surface fairing is limited to 0.055 mm per vertex, preserving calibre and the accepted course. Connected venous surfaces are faired together, with delicate native collars constrained. The venous deformation is damped to half the initial trial amplitude to retain a valid wall.','','The roof displacement is intentionally non-uniform: bone apposition, arterial spaces and native connections constrain it. This avoids treating the sinus as a uniformly scaled object. All existing selectable labels and topology are retained.','','| Posterior section | Mean upper-surface lowering, right | Left |','| --- | ---: | ---: |']
for i in range(2):lines.append(f"| y={measured[0]['slices'][i]['yMm']} mm | {measured[0]['slices'][i]['meanUpperSurfaceDisplacementMm']:.2f} mm | {measured[1]['slices'][i]['meanUpperSurfaceDisplacementMm']:.2f} mm |")
lines+=['','These are atlas-coordinate measurements of the original upper decile of surface vertices in each section, not patient measurements. Some protected branch corridors remain at their original height.','','## Verification','','- Complete ophthalmic and superior hypophyseal meshes, their topology and incident parent-wall coordinates are unchanged.',f'- All {njoins} documented physical joins pass, including sinus tributaries and the affected arterial branch collars.','- Zero detected non-adjacent intersections on either corrected ICA wall and on the changed regional venous network.','- No detected contacts between the two corrected ICA regions or cavernous sinus labels and retained bone.','- All 30 recorded local arterial branch/sinus contact checks pass.',f"- Sampled parent-artery/sinus surface gaps are {space[0]['sampledMinimumSurfaceGapMm']:.3f} mm right and {space[1]['sampledMinimumSurfaceGapMm']:.3f} mm left.",'- No degenerate output triangles; finite positions and unit normals.','- Production build and actual Three.js GLTFLoader/MeshoptDecoder checks pass. Unchanged mesh positions and indices remain exact.','','## Review limits','','Bone and brain geometry remain fixed. Dural boundaries are estimates, and native lower petrous/canal contacts remain outside this local refinement. Geometry checks are sampled or tolerance-limited and do not establish independent anatomical approval. Comparison renders come from decoded final production assets, with bone cut away for display only.','','Detailed evidence is in `anatomy/source/ica-cs-v0933`. Reproduction instructions and the constrained authoring scripts are in `tools/ica-cs-v0933`.']
(APP/'docs/ICA_CS_v0.9.33.md').write_text('\n'.join(lines)+'\n')
p=APP/'CHANGELOG.md';s=p.read_text();p.write_text('# v0.9.33: smaller posterior sinus and smoother local connections\n\nReduced posterior venous bulk, constrained fairing of connected arterial/venous surfaces, fixed ophthalmic anatomy and retained native joins. Includes final exported-mesh comparisons and measured local checks. See docs/ICA_CS_v0.9.33.md.\n\n'+s)
for p in OUT.glob('*.json'):shutil.copy2(p,APP/'anatomy/source/ica-cs-v0933'/p.name)
