from model import *
from fit import paths
from scipy.interpolate import CubicSpline
from scipy.ndimage import map_coordinates,gaussian_filter1d
from scipy.spatial import cKDTree
results=[];bone=combine(['bone.sphenoid','bone.temporal.right','bone.temporal.left'])
for side in ['right','left']:
 v,f=load('ICA cavernous '+side,True);g=np.load(OUT/('cavity-'+side+'.npz'));mx=-1e9
 for start in range(0,len(f),2000):
  t=v[f[start:start+2000]];pp=np.concatenate([t[:,0],t[:,1],t[:,2],(t[:,0]+t[:,1])/2,(t[:,0]+t[:,2])/2,(t[:,1]+t[:,2])/2,t.mean(1),t[:,0]*.6+t[:,1]*.2+t[:,2]*.2,t[:,0]*.2+t[:,1]*.6+t[:,2]*.2,t[:,0]*.2+t[:,1]*.2+t[:,2]*.6]);d=map_coordinates(g['outer'],((pp-g['lo'])/g['spacing']).T,order=1,mode='constant',cval=100);mx=max(mx,float(d.max()))
 q=np.load(OUT/'target-course.npz')[side];u=np.linspace(0,1,3000);sp=CubicSpline(np.linspace(0,1,len(q)),q);p=sp(u);der=sp(u,1);dd=sp(u,2);R=np.linalg.norm(der,axis=1)**3/np.maximum(np.linalg.norm(np.cross(der,dd),axis=1),1e-10);rad=np.load(ROOT/('centreline-'+side+'.npz'))['radius'];rad=np.interp(u,np.linspace(0,1,len(rad)),gaussian_filter1d(np.clip(rad,2.15,2.65),4));active=(p[:,2]>59)&(p[:,2]<77.3);ratio=float((R[active]/rad[active]).min())
 oa,of=load('Ophthalmic '+side);orig,pf=load('ICA paraophthalmic '+side);key=lambda a:np.ascontiguousarray(a.astype('<f4')).view('V12').ravel();ost=np.intersect1d(key(oa),key(orig));centre=ost.view('<f4').reshape(-1,3).mean(0);old=paths[side][0](u);oi=cKDTree(old).query(centre)[1];ni=cKDTree(p).query(centre)[1];arc=lambda p:np.r_[0,np.cumsum(np.linalg.norm(np.diff(p,axis=0),axis=1))];native=float(arc(old)[oi]-arc(old)[np.argmin(abs(u-.53))]);new=float(arc(p)[ni]-arc(p)[np.argmin(abs(u-.67))]);incident=pf[np.any(np.isin(key(orig)[pf],ost),axis=1)];newv,newf=arrays(combine(['ICA cavernous '+side,'ICA paraophthalmic '+side],True));trikey=lambda v,f:set(tuple(sorted(keys.tolist())) for keys in key(v)[f]);collars=len(trikey(orig,incident)&trikey(newv,newf));cv,cf=load('vein.cavernous.'+side,True);ica=combine(['ICA cavernous '+side,'ICA paraophthalmic '+side,'ICA petrous '+side],True);cl=locator(ica);pp=cv[::max(1,len(cv)//3000)];clearance=min(closest(cl,x)[1] for x in pp);inter=contacts(poly(cv,cf),ica)
 # Retained source-bone limitations outside the fitted C4 scope.
 lowv,lowf=load('ICA petrous '+side,True);lowv,lowf=clip(lowv,lowf,lowv[:,2]-55.4,False);lower=contacts(poly(lowv,lowf),bone);oldLow=combine(['ICA petrous '+side,'ICA cavernous '+side]);ol,olf=arrays(oldLow);ol,olf=clip(ol,olf,ol[:,2]-55.4,False);baselineLower=contacts(poly(ol,olf),bone);oldV,oldF=arrays(oldLow);nf=lowf[np.all(lowv[lowf,2]<55.399,axis=1)];og=oldF[np.all(oldV[oldF,2]<55.399,axis=1)];lowerExact=trikey(oldV,og)<=trikey(lowv,nf)
 results.append({'side':side,'containmentMaximumSdfMm':mx,'containmentSampling':'Vertices, all edge midpoints, centroid, three interior barycentric samples per triangle','containmentToleranceMm':.04,'minimumCurvatureRadiusOverTubeRadius':ratio,'curvatureScope':'Reconstructed tube z59–77.3 mm, before native collar graft','nativeGenuToOstiumArcMm':native,'revisedGenuToOstiumArcMm':new,'genuStations':'Source anterior genu u0.53; fitted anterior bend u0.67; OA projected on each centreline','sourceOstialParentFaces':len(incident),'preservedOstialParentFaces':collars,'arterySinusContacts':inter,'sampledMinimumArteryToSinusMm':clearance,'retainedLowerPetrousBoneContacts':lower,'baselineLowerPetrousBoneContacts':baselineLower,'lowerSourceFacesPreserved':lowerExact,'passed':mx<.04 and ratio>1 and new<=native and collars==len(incident) and inter==0 and clearance>.1 and lowerExact});print(results[-1],flush=True)
(OUT/'extra-checks.json').write_text(json.dumps(results,indent=2));r=json.load(open(OUT/'validation.json'));r['checks']['fullSurfaceConstraints']={'passed':all(x['passed'] for x in results),'sides':results};joins=json.load(open(OUT/'catalogue-joins.json'));r['checks']['cataloguePhysicalJoins']={'passed':all(x['passed'] for x in joins),'junctions':joins};r['passed']=all(x['passed'] for x in r['checks'].values());(OUT/'validation.json').write_text(json.dumps(r,indent=2))
