from model import *
from scipy.spatial import cKDTree
from scipy.ndimage import map_coordinates,gaussian_filter1d
from scipy.interpolate import CubicSpline
import hashlib
checks={};bones=['bone.sphenoid','bone.temporal.right','bone.temporal.left'];bone=combine(bones);bonechecks=[];protected=[];calibres=[];joins=[];meshq=[]
for side in ['right','left']:
 oa,of=load('Ophthalmic '+side);oa2,of2=load('Ophthalmic '+side,True);parent,pf=load('ICA paraophthalmic '+side,True);orig,ff=load('ICA paraophthalmic '+side);keys=lambda a:np.ascontiguousarray(a.astype('<f4')).view('V12').ravel();shared=np.intersect1d(keys(oa),keys(orig));kept=np.intersect1d(shared,keys(parent));protected.append({'side':side,'completeOphthalmicMeshExact':np.array_equal(oa,oa2) and np.array_equal(of,of2),'ostialVertices':len(shared),'ostialVerticesPreserved':len(kept),'passed':np.array_equal(oa,oa2) and len(shared)==len(kept)})
 for name in ['ICA cavernous '+side,'vein.cavernous.'+side]:
  a=combine([name],True);num=contacts(a,bone);bonechecks.append({'mesh':name,'boneContacts':num,'passed':num==0});print('Bone',name,num,flush=True)
 g=np.load(OUT/('cavity-'+side+'.npz'));q=np.load(OUT/'target-course.npz')[side];qq=q[(np.linspace(0,1,len(q))>.54)&(np.linspace(0,1,len(q))<.70)];d=map_coordinates(g['outer'],((qq-g['lo'])/g['spacing']).T,order=1,mode='constant',cval=100);origRad=np.load(ROOT/('centreline-'+side+'.npz'))['radius'];newRad=gaussian_filter1d(np.clip(origRad,2.15,2.65),4);rawRatio=newRad/origRad;ru=np.linspace(0,1,len(origRad));tq=CubicSpline(np.linspace(0,1,len(q)),q)(ru);mask=(tq[:,2]>59)&(tq[:,2]<77.3);ratio=rawRatio[mask];calibres.append({'side':side,'method':'Source centreline radius profile, Gaussian smoothing sigma=4 samples; bounded 2.15–2.65 mm reconstruction','calibreScope':'Reconstructed main tube z59–77.3 mm; truncated source centreline endpoint estimates are excluded because those regions are replaced by preserved native collars','rawEndpointInclusiveRatioP05MedianP95':np.percentile(rawRatio,[5,50,95]).tolist(),'ratioP05MedianP95':np.percentile(ratio,[5,50,95]).tolist(),'p95AbsoluteFractionalRadiusChange':float(np.percentile(np.abs(ratio-1),95)),'genuCentreMaximumOuterSdfMm':float(d.max()),'genuInsideIndependentBody':bool(d.max()<0),'calibrePassed':bool(np.percentile(np.abs(ratio-1),95)<.10)})
 for child,parent in [('Ophthalmic '+side,'ICA paraophthalmic '+side),('Superior hypophyseal '+side,'ICA paraophthalmic '+side),('Meningohypophyseal trunk '+side,'ICA cavernous '+side),('Inferolateral trunk '+side,'ICA cavernous '+side),('ICA cavernous '+side,'ICA paraophthalmic '+side),('ICA petrous '+side,'ICA cavernous '+side)]:
  x,_=load(child,True);y,_=load(parent,True);n=len(np.intersect1d(keys(x),keys(y)));joins.append({'a':child,'b':parent,'sharedVertices':n,'passed':n>=3})
 for stem in ['superior_petrosal','inferior_petrosal','superior_ophthalmic','sphenoparietal','superficial_middle_cerebral','ovale_emissary','anterior_intercavernous','posterior_intercavernous','basilar_plexus']:
  n='vein.'+stem+('.'+side if stem not in ['anterior_intercavernous','posterior_intercavernous','basilar_plexus'] else '');x,_=load(n,True);y,_=load('vein.cavernous.'+side,True);count=len(np.intersect1d(keys(x),keys(y)));joins.append({'a':n,'b':'vein.cavernous.'+side,'sharedVertices':count,'passed':count>=3})
for row in META:
 name=row['name']
 if not (OUT/(name+'.positions.bin')).exists():continue
 v,f=load(name,True);n=np.fromfile(OUT/(name+'.normals.bin'),'<f4').reshape(-1,3);t=v[f];area=np.linalg.norm(np.cross(t[:,1]-t[:,0],t[:,2]-t[:,0]),axis=1);passed=bool(np.isfinite(v).all() and np.isfinite(n).all() and (area>1e-12).all() and (np.abs(np.linalg.norm(n,axis=1)-1)<.002).all());meshq.append({'mesh':name,'vertices':len(v),'triangles':len(f),'minimumDoubleAreaMm2':float(area.min()),'passed':passed})
checks['protectedOphthalmic']={'passed':all(r['passed'] for r in protected),'sides':protected};checks['boneClearance']={'passed':all(r['passed'] for r in bonechecks),'meshes':bonechecks};checks['physicalJunctions']={'passed':all(r['passed'] for r in joins),'junctions':joins};checks['meshQuality']={'passed':all(r['passed'] for r in meshq),'meshes':meshq};checks['selfIntersections']={'passed':all(r['nonAdjacentIntersections']==0 for r in json.load(open(OUT/'self-intersections.json'))),'sides':json.load(open(OUT/'self-intersections.json'))};checks['calibreAndGenu']={'passed':all(r['genuInsideIndependentBody'] and r['calibrePassed'] for r in calibres),'sides':calibres};checks['remoteVenousSplices']={'passed':all(r['passed'] for r in json.load(open(OUT/'venous-splices.json'))),'splices':json.load(open(OUT/'venous-splices.json'))};checks['boneRegistration']={'passed':all(not (OUT/(n+'.positions.bin')).exists() for n in bones),'scope':'Bone assets and positions unchanged'}
r={'release':'0.9.32','passed':all(c['passed'] for c in checks.values()),'checks':checks,'limitations':['Estimated petrolingual entry and proximal dural boundary; no segmented dura.','Native lower petrous/canal bone contacts retained from source below fitted cavernous region; unresolved source bone canals.','Anatomical review pending; modelling revision, not patient-specific validation.']};(OUT/'validation.json').write_text(json.dumps(r,indent=2));print('Validation',r['passed'],[(k,c['passed']) for k,c in checks.items()],flush=True);print('Joins failed',[r for r in joins if not r['passed']],flush=True)
