"""Bind accepted new meshes and honest course review metadata to the catalogue."""
import json,hashlib,sys
from pathlib import Path
ROOT=Path.cwd();WORK=Path(sys.argv[1]);OUT=WORK/'candidate';p=ROOT/'anatomy/generated/complete_manifest.json';m=json.loads(p.read_text());rev=json.loads((OUT/'revision.json').read_text());paths=json.loads((OUT/'new-vein-paths.json').read_text());m['release']='0.9.50';rows={s['id']:s for s in m['structures']}
sources=[dict(id='ref.magro2015',title='Magro et al. Venous organization in the transverse foramen: dissection, histology and MRI. 2015.',url='https://doi.org/10.3171/2014.10.JNS14906',role='Selected ventrolateral vertebral venous plexiform reference anatomy'),dict(id='ref.sanmillan2004',title='San Millán Ruíz et al. The sphenoparietal sinus of Breschet: does it exist? 2004.',url='https://pubmed.ncbi.nlm.nih.gov/14729539/',role='Paired anterior middle meningeal veins, distinguished from superficial middle cerebral drainage'),dict(id='ref.mazzoni2025',title='Mazzoni et al. Internal auditory canal venous anatomy. 2025.',url='https://doi.org/10.14639/0392-100X-A1054',role='Selected CPA drainage towards the petrosal vein, distinct from intrabony venous drainage'),dict(id='ref.venous-audit-v0950',title='Regional venous reference reconstruction and audit continuation, v0.9.50',role='Local authoring paths and exact geometry checks',notes='Reference teaching reconstructions with illustrative radii. Not patient anatomy or complete canal segmentation; see docs/AUDIT_CONTINUATION_v0.9.50.md.'),dict(id='ref.pterygoid2021',title='Cadaveric infratemporal fossa vascular study',url='https://pmc.ncbi.nlm.nih.gov/articles/PMC8563275/',role='Regional pterygoid plexus anatomy'),dict(id='ref.barrow-cavernous',title='Barrow Neurological Institute: Microsurgical anatomy of the cavernous sinus',url='https://www.barrowneuro.org/for-physicians-researchers/education/grand-rounds-publications-media/barrow-quarterly/volume-12-no-2-1996/microsurgical-anatomy-of-the-cavernous-sinus/',role='Retinal and ophthalmic venous drainage reference')]
m['sources'] += [s for s in sources if s['id'] not in {x['id'] for x in m['sources']}]
labels={'inferior_alveolar':'Inferior alveolar vein','infraorbital':'Infraorbital vein','internal_auditory':'Internal auditory vein, selected CPA route','central_retinal':'Central retinal vein, superior ophthalmic variant','middle_meningeal':'Paired anterior middle meningeal veins','vertebral_periarterial_plexus':'Vertebral periarterial venous plexus'}
sources_extra=[dict(id='ref.orbital2003',title='Venous anatomy of the orbit, cadaveric study, 2003',url='https://pubmed.ncbi.nlm.nih.gov/12601019/',role='Orbital venous anatomy and variability'),dict(id='ref.pterygoid1996',title='The pterygoid venous plexuses, cadaveric study, 1996',url='https://pubmed.ncbi.nlm.nih.gov/8685807/',role='Pterygoid venous anatomy')]
m['sources'] += [s for s in sources_extra if s['id'] not in {x['id'] for x in m['sources']}]
refs={'inferior_alveolar':['ref.pterygoid2021'],'infraorbital':['ref.pterygoid2021'],'internal_auditory':['ref.mazzoni2025'],'central_retinal':['ref.barrow-cavernous','ref.orbital2003'],'middle_meningeal':['ref.sanmillan2004'],'vertebral_periarterial_plexus':['ref.magro2015']}
for route in paths:
 node=route['node']
 if node not in rev['newLabels']:continue
 family=route['family'];side=route['side'];parent=route['attachment']['receiver'];relationship=dict(**{'from':node,'to':parent,'type':'communicates_with' if family=='vertebral_periarterial_plexus' else 'drains_to'},note='Selected represented reference connection; separate contacting vessel surfaces.')
 if relationship not in m['relationships']:m['relationships'].append(relationship)
 description={'inferior_alveolar':'The inferior alveolar veins drain the mandibular region towards the pterygoid plexus. This model shows a selected proximal canal corridor and drainage stem; dental tributaries are omitted.','infraorbital':'The infraorbital vein drains the infraorbital region towards the pterygoid plexus. This is a selected reference course alongside the arterial corridor.','internal_auditory':'Internal auditory venous drainage varies. This model shows a selected route from the meatal region through the cerebellopontine angle to the superior petrosal vein. Separate intrabony drainage and cochlear or vestibular aqueduct veins are omitted.','central_retinal':'The central retinal vein accompanies the retinal vessels in the optic nerve. This model represents a selected superior ophthalmic drainage variant; direct cavernous drainage is another pattern. The globe and optic nerve are not modelled.','middle_meningeal':'Paired middle meningeal veins flank the anterior arterial branch. This model shows selected anterior companion channels draining towards the pterygoid plexus. These are distinct from superficial middle cerebral venous drainage.','vertebral_periarterial_plexus':'A regional plexiform venous arrangement lies ventrolateral to the vertebral artery and communicates with the dominant vertebral venous collector. This model shows selected longitudinal and cross-connecting channels. Cervical vertebrae, exact level transitions and the complete microscopic plexus are not modelled.'}[family]
 s=dict(id=node,name=labels[family]+' '+side,parent=parent,side=side,aliases=[],color='#416aa8',system='vein',kind='structure',children=[],geometryStatus='web-optimised',provenance=dict(sourceType='teaching-reconstruction',confidence='Selected reference pattern; illustrative calibre and regional course',reviewStatus='unreviewed',sourceRefs=refs[family]+['ref.venous-audit-v0950']),asset=dict(file='models/venous.glb',node=node),notes='Reference teaching reconstruction. '+route['scope']+'.',description=description)
 s['vesselCourse']=dict(vesselId=node,side=side,scope='reference-corridor',geometry=s['asset'],geometrySha256='',registrationId=m['brainRegistration']['id'],brainAssetSha256=m['brainRegistration']['registeredAssetSha256'],attachments=dict(parentId=parent,incoming=[],outgoing=[relationship],status='selected-reference-volume-attachment'),radiusPolicy='preserve-delivered-profile',reviewStatus='requires-anatomical-review',segments=[],missingTargets=[],summary=description,targetStructureIds=[],stationIds=[],stationOrder='not-applicable',candidateReviewStatus='Reference reconstruction. Full anatomical and canal containment review remains pending.',referencePathSource='anatomy/source/audit-finish-v0950/new-vein-paths.json')
 if node in rows: m['structures'][m['structures'].index(rows[node])]=s
 else:m['structures'].append(s)
 rows[node]=s
 if node not in rows[parent]['children']:rows[parent]['children'].append(node)
hashes={file:hashlib.sha256((ROOT/'public/anatomy'/file).read_bytes()).hexdigest() for file in m['assetRevisions']}
for s in m['structures']:
 c=s.get('vesselCourse')
 if not c:continue
 c['attachments']['incoming']=[r for r in m['relationships'] if r['to']==s['id']]
 c['attachments']['outgoing']=[r for r in m['relationships'] if r['from']==s['id']]
 if s.get('asset'):
  file=s['asset']['file'];c['geometrySha256']=hashes[file]
 if s.get('asset',{}).get('node') in {r['node'] for r in rev['changed'] if r['node'] not in rev['newLabels']}:
  c['radiusPolicy']='preserve-delivered-profile';c['reviewStatus']='requires-anatomical-review';c['candidateReviewStatus']='Constrained local shaft fitting; native shared collars fixed. Regional anatomy review remains open.'
for file in m['assetRevisions']:
 b=(ROOT/'public/anatomy'/file).read_bytes();m['assetRevisions'][file]=hashlib.sha256(b).hexdigest()[:20];m['assetByteSizes'][file]=len(b)
m['relationshipCorrections']=dict(release='0.9.50',baseline='0.9.49',changedNodes=[r['node'] for r in rev['changed']],newLabels=rev['newLabels'],auditStatus='partially-implemented-with-explicit-open-items',documentation='docs/AUDIT_CONTINUATION_v0.9.50.md',wholeAtlasWatertight=False)
p.write_text(json.dumps(m,indent=2)+'\n');export=ROOT/'public/anatomy/vessel-courses.json';d=json.loads(export.read_text());d['release']='0.9.50';d['courses']=[s['vesselCourse'] for s in m['structures'] if s.get('vesselCourse')];export.write_text(json.dumps(d,indent=2)+'\n');dest=ROOT/'anatomy/source/audit-finish-v0950';dest.mkdir(parents=True,exist_ok=True);(dest/'new-vein-paths.json').write_text(json.dumps(paths,indent=2)+'\n');(dest/'revision.json').write_text(json.dumps(rev,indent=2)+'\n')
print('Bound',len(rev['newLabels']),'new selectable venous labels')
