"""Selected central retinal and paired anterior meningeal reference veins."""
from vein_geometry import *
revision=json.loads((OUT/'revision.json').read_text());families=['central_retinal','middle_meningeal'];replace={'vein.'+family+'.'+side for family in families for side in ['right','left']};revision['newLabels']=[n for n in revision['newLabels'] if n not in replace];revision['changed']=[r for r in revision['changed'] if r['node'] not in replace];paths=[p for p in json.loads((OUT/'new-vein-paths.json').read_text()) if p['node'] not in replace]
for side,sign in [('right',1),('left',-1)]:
 name='Central retinal '+side;q=np.load(WORK/(name+'.curve.npz'))['q'];q=(q if q[0,1]>q[-1,1] else q[::-1])+[sign*.36,0,.1];receiver='vein.superior_ophthalmic.'+side;q,attachment=connect(q,receiver);q,adjust=repel_arteries(q,.13,receiver);v,f=tube(q,np.full(len(q),.13));node='vein.central_retinal.'+side;write(node,v,f);revision['newLabels'].append(node);revision['changed'].append(dict(node=node,file='venous.glb',vertices=len(v),triangles=len(f),topology='new closed smooth reference tube'));paths.append(dict(node=node,family='central_retinal',side=side,points=q.tolist(),radiusMm=.13,arterialClearanceAdjustmentMm=adjust,attachment=attachment,sourceCorridor=name,scope='selected superior ophthalmic drainage variant; globe and optic nerve are absent, intraneural fit unverified'));print('Built',node,flush=True)
 name='Middle meningeal'+(' left' if side=='left' else '');a=np.load(WORK/(name+'.curve.npz'))['q'];b=np.load(WORK/('MMA frontal'+(' left' if side=='left' else '')+'.curve.npz'))['q'];a=a if a[0,2]<a[-1,2] else a[::-1];b=b if b[0,2]<b[-1,2] else b[::-1];q=resample(np.vstack([a[a[:,2]>40],b[b[:,2]>a[-1,2]+.4]]));bone='bone.parietal.'+side;cp,dd=closest(locator(*load(bone)),q);towards=cp-q;tangent=np.gradient(q,axis=0);offset=np.cross(tangent,towards);offset/=np.maximum(np.linalg.norm(offset,axis=1)[:,None],1e-8);offset=gaussian_filter1d(offset,2,axis=0);offset/=np.maximum(np.linalg.norm(offset,axis=1)[:,None],1e-8);vs=[];fs=[];routes=[];attachments=[];adjustments=[];receiver='vein.pterygoid_plexus.'+side
 for sign2 in [-1,1]:
  p=(q+offset*sign2*1.15)[::-1];p,attachment=connect(p,receiver,avoid_points=[x['surfaceEntryPoint'] for x in attachments] if attachments else None);p,adjust=repel_arteries(p,.23,receiver);v,f=tube(p,np.full(len(p),.23));fs.append(f+sum(len(x) for x in vs));vs.append(v);routes.append(p.tolist());attachments.append(attachment);adjustments.append(adjust)
 v=np.concatenate(vs);f=np.concatenate(fs);node='vein.middle_meningeal.'+side;write(node,v,f);revision['newLabels'].append(node);revision['changed'].append(dict(node=node,file='venous.glb',vertices=len(v),triangles=len(f),topology='two independently closed paired anterior meningeal reference tubes'));paths.append(dict(node=node,family='middle_meningeal',side=side,points=routes,radiusMm=.23,arterialClearanceAdjustmentMm=max(adjustments),attachment={'receiver':receiver,'routes':attachments},sourceCorridor=name+' and anterior branch',scope='selected paired anterior meningeal veins and extracranial drainage stems; other meningeal veins and foraminal containment unverified'));print('Built',node,flush=True)
(OUT/'revision.json').write_text(json.dumps(revision,indent=2)+'\n');(OUT/'new-vein-paths.json').write_text(json.dumps(paths,indent=2)+'\n')
