import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {MeshoptDecoder} from 'meshoptimizer';
await MeshoptDecoder.ready;const candidate=path.resolve(process.argv[2]??'../fixes-work/candidate'),baseline=path.resolve(process.argv[3]??'../audit-work/decoded');const report=JSON.parse(fs.readFileSync(path.join(candidate,'revision.json'))),changed=new Set(report.changed.map(r=>r.node));const checks=[];
for(const filename of [...new Set(report.changed.map(r=>r.file))]){
const data=fs.readFileSync('public/anatomy/models/'+filename);const loader=new GLTFLoader();loader.setMeshoptDecoder(MeshoptDecoder);const gltf=await loader.parseAsync(data.buffer.slice(data.byteOffset,data.byteOffset+data.byteLength),'');let labels=0,triangles=0;
gltf.scene.traverse(o=>{if(!o.isMesh)return;const a=gltf.parser.associations.get(o),name=gltf.parser.json.nodes[a.nodes].name,g=o.geometry,pos=g.attributes.position,index=g.index;const dir=changed.has(name)?candidate:baseline;const p=fs.readFileSync(path.join(dir,name+'.positions.bin')),f=fs.readFileSync(path.join(dir,name+'.indices.bin'));assert.equal(p.length,pos.count*12,name);assert.equal(f.length,index.count*4,name);for(let i=0;i<pos.count;i++)for(let j=0;j<3;j++)assert.equal(pos.getComponent(i,j),p.readFloatLE(i*12+j*4),name+' positions');for(let i=0;i<index.count;i++)assert.equal(index.getX(i),f.readUInt32LE(i*4),name+' indices');if(changed.has(name)){const n=g.attributes.normal;for(let i=0;i<n.count;i++)assert(Math.abs(Math.hypot(n.getX(i),n.getY(i),n.getZ(i))-1)<.002,name+' normal');}labels++;triangles+=index.count/3;});
checks.push({file:filename,labels,triangles,sha256:crypto.createHash('sha256').update(data).digest('hex'),exactLoadedPositionsAndIndices:true,unitLoadedNormals:true});
}
const m=JSON.parse(fs.readFileSync('public/anatomy/manifest.json'));assert.equal(m.release,'0.9.49');for(const r of m.structures)if(r.vesselCourse){const c=checks.find(c=>'models/'+c.file===r.asset.file);if(c)assert.equal(r.vesselCourse.geometrySha256,c.sha256);}
const x={release:m.release,passed:true,checks,scope:'Actual Three.js GLTFLoader and MeshoptDecoder; all unchanged positions and indices remain exact.'};fs.writeFileSync(path.join(candidate,'loader.json'),JSON.stringify(x,null,2)+'\n');console.log(x);
